FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Rome

RUN apt-get update && \
    apt-get install software-properties-common -y && \
    add-apt-repository ppa:deadsnakes/ppa -y && \
    apt-get update && \
    apt-get install python3.10 python3.10-dev python3.10-venv python3-pip ffmpeg libsm6 libxext6 -y && \
    rm -rf /var/lib/apt/lists/*

ADD . /eyegway

WORKDIR /eyegway

RUN python3.10 -m pip install . \
    -f http://wheels.eyecan.ai:8000 --trusted-host wheels.eyecan.ai --no-cache-dir