ARG EYEGWAY_HOST="http://localhost:55221"
ARG WEBUI_TITLE="hello world"

FROM node:21

ENV VITE_EYEGWAY_HOST=:${EYEGWAY_HOST}
ENV VITE_WEBUI_TITLE=:${WEBUI_TITLE}

ADD . /eyegway

WORKDIR /eyegway/web/eyegway-svelte

RUN cd /eyegway/web/eyegway-svelte && yarn install && yarn build
