<script lang="ts">
	import PaneNode from './PaneNode.svelte';
	import StyleSettingsPanel from './settings/StyleSettingsPanel.svelte';
	import { Edit, Palette } from 'lucide-svelte';
	import { paneUtils, paneConfiguration } from './PaneStore.js';
	import { styleUtils } from './settings/SettingsStore.js';
	import SerializationControls from '../utils/SerializationControls.svelte';
	import { tick } from 'svelte';

	export let editMode: boolean = true;
	export let styleMode: boolean = false;
	export let dataStream: any = {};
	export let controls = true;

	let refreshStyle: boolean = false;
	let refreshPane: boolean = false;

	let refreshingPane: boolean = false;

	function toggleEditMode() {
		editMode = !editMode;
	}
	function toggleStyleMode() {
		styleMode = !styleMode;
	}

	function handleUpdate() {
		if (!refreshingPane && !refreshPane) $paneConfiguration.id = Date.now();
	}

	// This is a workaround to:
	// 1. Be able to refresh the PaneNode when the user changes the configuration
	// 2. Avoid interpreting the events generated by the PaneNode itself as user events
	// Feel free to find a better solution!
	$: if (refreshPane) {
		// Here we are starting refreshing the PaneNode
		// we need to wait for the PaneNode to finish refreshing
		refreshingPane = true;
		tick().then(() => {
			refreshPane = false;
			// In this moment it should have ended
			// but the #key refreshPane will trigger again
			tick().then(() => {
				refreshingPane = false;
				// Now we can restart listening to the events from the PaneNode
				// being sure that are generated by the user and not by the system
			});
		});
	}
</script>

<div class="panels">
	<div class="is-flex p-0 is-align-items-center is-justify-content-center" style="height: 100%">
		{#key refreshPane}
			<PaneNode
				draggingStep={1}
				bind:pane={$paneConfiguration}
				{editMode}
				{dataStream}
				tips={dataStream ? Object.keys(dataStream) : []}
				on:update={handleUpdate}
			/>
		{/key}
		<StyleSettingsPanel isDisabled={!styleMode} bind:refresh={refreshStyle} />
	</div>

	{#if controls}
		<div class="controls p-2" class:controls-hidden={!editMode && !styleMode}>
			<div class="columns is-vcentered is-variable is-1 is-mobile">
				<div class="column is-narrow">
					<div class="columns is-vcentered is-variable is-1 is-mobile">
						<div class="column is-narrow">
							<button
								class="button is-warning is-small"
								disabled={editMode}
								class:is-inverted={styleMode}
								on:click={toggleStyleMode}
								title="{styleMode ? 'Disable' : 'Enable'} Edit Mode"
							>
								<Palette size={16} />
							</button>
						</div>
						<div class="column is-narrow">
							<button
								class="button is-warning is-small"
								disabled={styleMode}
								class:is-inverted={editMode}
								on:click={toggleEditMode}
								title="{editMode ? 'Disable' : 'Enable'} Edit Mode"
							>
								<Edit size={16} />
							</button>
						</div>
					</div>
				</div>
				<div class="column is-narrow">
					{#if styleMode}
						<SerializationControls
							config={styleUtils}
							on:update={() => {
								refreshStyle = true;
							}}
						/>
					{/if}
					{#if editMode}
						<SerializationControls
							config={paneUtils}
							on:update={() => {
								refreshPane = true;
							}}
						/>
					{/if}
				</div>
			</div>
		</div>
	{/if}
</div>

<style>
	.panels {
		height: 100%;
		padding: 5px !important;
	}
	.panels .controls-hidden {
		display: none;
	}
	.panels:hover .controls-hidden {
		display: block;
	}
	.controls {
		margin-top: 4px;
	}
</style>
